"""initial

Revision ID: e7396e6f4ef2
Revises: 
Create Date: 2025-12-27 22:12:01.295769

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'e7396e6f4ef2'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # Intentionally no-op to avoid destructive changes on existing databases.
    # This migration was autogenerated; apply with caution. To create a safe
    # baseline in an environment with an existing schema, keep this upgrade
    # empty and use `alembic stamp head` in production-like databases.
    return


def downgrade() -> None:
    """Downgrade schema."""
    # No-op downgrade; destructive operations were removed to avoid data loss.
    return

